# Generated by Django 2.2.5 on 2021-08-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation_Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_id', models.IntegerField()),
                ('dataset_name', models.CharField(max_length=255)),
                ('sentences', models.CharField(max_length=255)),
                ('real_label', models.CharField(max_length=255)),
                ('predict_result', models.CharField(max_length=255)),
                ('candidate_label_1', models.CharField(default='label_1', max_length=255)),
                ('candidate_label_2', models.CharField(default='label_2', max_length=255)),
                ('candidate_label_3', models.CharField(default='label_3', max_length=255)),
                ('key_words', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Data_Note_Annotation_Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_id', models.IntegerField()),
                ('dataset_name', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('sentences', models.CharField(max_length=255)),
                ('real_label', models.CharField(max_length=255)),
                ('predict_result', models.CharField(max_length=255)),
                ('candidate_label_1', models.CharField(max_length=255)),
                ('candidate_label_2', models.CharField(max_length=255)),
                ('candidate_label_3', models.CharField(max_length=255)),
                ('key_words', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('class_num', models.BigIntegerField()),
                ('source', models.CharField(max_length=255)),
                ('paper_source', models.CharField(max_length=255)),
                ('local_path', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('sample_total_num', models.BigIntegerField()),
                ('sample_training_num', models.BigIntegerField()),
                ('sample_validation_num', models.BigIntegerField()),
                ('sample_test_num', models.BigIntegerField()),
                ('sentence_max_length', models.IntegerField()),
                ('sentence_avg_length', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hyper_parameters',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=255)),
                ('param_describe', models.CharField(max_length=255)),
                ('default_value', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
                ('run_value', models.CharField(max_length=255)),
                ('model_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_Tdes',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('paper_source', models.CharField(max_length=255)),
                ('code_source', models.CharField(max_length=255)),
                ('local_path', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_Test_Example',
            fields=[
                ('example_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentences', models.CharField(max_length=255)),
                ('ground_truth', models.CharField(max_length=255)),
                ('predict_result', models.CharField(max_length=255)),
                ('candidate_label_1', models.CharField(default='label_1', max_length=255)),
                ('candidate_label_2', models.CharField(default='label_2', max_length=255)),
                ('candidate_label_3', models.CharField(default='label_3', max_length=255)),
                ('key_words', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='run_log_hyper_parameters',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=255)),
                ('param_describe', models.CharField(max_length=255)),
                ('default_value', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
                ('run_value', models.CharField(max_length=255)),
                ('log_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Run_Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('Annotated_ratio', models.CharField(max_length=255)),
                ('Intent_Ratio', models.CharField(max_length=255)),
                ('Local_Path', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('run_pid', models.CharField(max_length=255)),
                ('model_id', models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_tdes', to='thedataset.Model_Tdes')),
            ],
        ),
    ]
