# Generated by Django 2.2.5 on 2021-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedataset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='paper_source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
