# Generated by Django 2.2.5 on 2021-08-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thedataset', '0002_auto_20210810_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='paper_source',
            new_name='papers_source',
        ),
    ]
