# Generated by Django 2.2.5 on 2021-08-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thedataset', '0003_auto_20210810_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run_log',
            name='model_id',
        ),
    ]
