# Generated by Django 2.2.5 on 2021-08-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thedataset', '0004_remove_run_log_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='run_log',
            name='model_id',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_tdes', to='thedataset.Model_Tdes'),
        ),
    ]
