# Generated by Django 2.2.5 on 2021-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedataset', '0006_remove_dataset_papers_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='sentence_avg_length',
            field=models.FloatField(),
        ),
    ]
