# Generated by Django 2.2.5 on 2021-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedataset', '0007_auto_20210810_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='sentence_avg_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
