# Generated by Django 2.2.5 on 2021-08-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedataset', '0008_auto_20210810_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='sentence_avg_length',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
